name: ReleaseTest

on:
  push:
    branches: ["feature/v2-preview"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      - name: Check if version has been updated
        id: check
        uses: EndBug/version-check@v2

      - name: Install dependencies
        if: steps.check.outputs.changed == 'true'
        run: npm ci

      - name: Build
        if: steps.check.outputs.changed == 'true'
        run: npm run build

      - name: Copy public
        if: steps.check.outputs.changed == 'true'
        run: cp -r public/* dist/

      - name: Create release
        if: steps.check.outputs.changed == 'true'
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.check.outputs.version}}"
          prerelease: false
          title: "Development Build"
          files: Readme.MD
